# Generated by Django 5.1.3 on 2025-01-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nicName', models.CharField(default='123', max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('birthday', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=10)),
                ('mdate', models.DateTimeField(auto_now=True)),
                ('created_group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='diary.groupdiary')),
                ('joined_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='diary.groupdiary')),
            ],
        ),
    ]
