# Generated by Django 5.1.3 on 2025-01-10 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('ctitle', models.CharField(max_length=1000)),
                ('ccontent', models.TextField(null=True)),
                ('cdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary_images/')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gno', models.IntegerField(default=0)),
                ('gtitle', models.CharField(max_length=200)),
                ('gName', models.CharField(default='우리 가족', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('lno', models.AutoField(primary_key=True, serialize=False)),
                ('ltitle', models.CharField(max_length=1000)),
                ('lcontent', models.TextField()),
                ('ldate', models.DateTimeField(auto_now=True)),
                ('lhit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MdiaryBoard',
            fields=[
                ('mno', models.AutoField(primary_key=True, serialize=False)),
                ('mtitle', models.CharField(default='나의 일기장', max_length=1000)),
                ('mdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
