# Generated by Django 5.1.3 on 2025-01-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member'),
        ),
        migrations.AddField(
            model_name='groupdiary',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member'),
        ),
        migrations.AddField(
            model_name='content',
            name='group_diary',
            field=models.ManyToManyField(blank=True, to='diary.groupdiary'),
        ),
        migrations.AddField(
            model_name='letter',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member'),
        ),
        migrations.AddField(
            model_name='mdiaryboard',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginpage.member'),
        ),
        migrations.AddField(
            model_name='content',
            name='mdiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.mdiaryboard'),
        ),
    ]
