# Generated by Django 5.1.3 on 2025-01-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_like_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='content',
        ),
    ]
